spring:
  profiles:
    active: local
    group:
      local: common, secret
---
server:
  port: 8088
  servlet:
    encoding:
      force-response: true

logging:
  level:
    com.boot.first: info

upload:
  path: "abookz/src/main/resources/static/images/"

spring:
  config:
    activate:
      on-profile: common

  mvc:
    view:
      prefix: templates/
      suffix: .html
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
      #ddl-auto: create
      #show_sql: true
      #format_sql: true
      use_sql_comments: true
      highlight_sql: true

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

  mail:
    host: smtp.naver.com
    port: 465
    username: dbalstjr97@naver.com
    password: youminseuk97
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
